[package]
name = "ciphrchat-routing"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
libp2p = { version = "0.53.2", features = ["tcp", "quic", "noise", "yamux", "identify", "tokio", "macros", "relay", "dcutr", "request-response", "cbor"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
futures = "0.3"

[features]
server = []

[[bin]]
name = "ciphrchat-server"
path = "src/main.rs"
required-features = ["server"]
